apiVersion: v1
kind: PersistentVolume
metadata:
  name: eclipsechewksp
  labels:
    type: local
spec:
  storageClassName: eclipsechewksp
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/wksp"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    type: local
spec:
  storageClassName: eclipseche
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: eclipsechewksp
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: eclipseche
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Retain
---
kind: Namespace
apiVersion: v1
metadata:
  name: chewksp
